In [4]:
!uv add -q polars numpy SPARQLWrapper gensim python-dotenv kagglehub[polars-datasets] ipywidgets sentence-transformers

__IMPORTING REQUIRED LIBRARIES__

_Required libraries (fix order):_
1. polars (replacing pandas (novelty))
2. numpy
3. gensim
4. sentence-transformers
5. matplotlib
6. scikit-learn
7. os
8. dotenv
9. kagglehub
10. torch (for cuda)

In [3]:
import os
from dotenv import load_dotenv

import polars as pl
import numpy
import gensim
import torch

In [4]:
wv = gensim.models.KeyedVectors.load_word2vec_format('word2vec_format/GoogleNews-vectors-negative300.bin', binary=True)

__LOADING DATASET__

_Dataset Details:_
1. Name - ISOT Fake News Dataset
2. Link - https://www.kaggle.com/datasets/emineyetm/fake-news-detection-datasets/data
3. Number of rows - 20,826 (True) and 17,903 (False)

In [5]:
load_dotenv()

kaggle_key = os.getenv('KAGGLE_API_TOKEN')
kaggle_username = os.getenv('KAGGLE_USERNAME')

In [6]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [7]:
path = kagglehub.dataset_download("emineyetm/fake-news-detection-datasets", output_dir='./dataset')

In [8]:
true_df = pl.read_csv('dataset/News _dataset/True.csv')
fake_df = pl.read_csv('dataset/News _dataset/Fake.csv')

In [9]:
true_df.head()

shape: (5, 4)
┌───────────────┬───────────────┬──────────────┬───────────────┐
│ title         ┆ text          ┆ subject      ┆ date          │
│ ---           ┆ ---           ┆ ---          ┆ ---           │
│ str           ┆ str           ┆ str          ┆ str           │
╞═══════════════╪═══════════════╪══════════════╪═══════════════╡
│ As U.S.       ┆ WASHINGTON    ┆ politicsNews ┆ December 31,  │
│ budget fight  ┆ (Reuters) -   ┆              ┆ 2017          │
│ looms, Re…    ┆ The hea…      ┆              ┆               │
│ U.S. military ┆ WASHINGTON    ┆ politicsNews ┆ December 29,  │
│ to accept     ┆ (Reuters) -   ┆              ┆ 2017          │
│ transg…       ┆ Transge…      ┆              ┆               │
│ Senior U.S.   ┆ WASHINGTON    ┆ politicsNews ┆ December 31,  │
│ Republican    ┆ (Reuters) -   ┆              ┆ 2017          │
│ senator…      ┆ The spe…      ┆              ┆               │
│ FBI Russia    ┆ WASHINGTON    ┆ politicsNews ┆ December 30,  │
│ probe helped  ┆ (Reuters) -   ┆              ┆ 2017          │
│ by Aus…       ┆ Trump c…      ┆              ┆               │
│ Trump wants   ┆ SEATTLE/WASHI ┆ politicsNews ┆ December 29,  │
│ Postal        ┆ NGTON         ┆              ┆ 2017          │
│ Service to …  ┆ (Reuters) -…  ┆              ┆               │
└───────────────┴───────────────┴──────────────┴───────────────┘

In [10]:
true_df = true_df.drop('date')
true_df.head()

shape: (5, 3)
┌───────────────────────┬───────────────────────┬──────────────┐
│ title                 ┆ text                  ┆ subject      │
│ ---                   ┆ ---                   ┆ ---          │
│ str                   ┆ str                   ┆ str          │
╞═══════════════════════╪═══════════════════════╪══════════════╡
│ As U.S. budget fight  ┆ WASHINGTON (Reuters)  ┆ politicsNews │
│ looms, Re…            ┆ - The hea…            ┆              │
│ U.S. military to      ┆ WASHINGTON (Reuters)  ┆ politicsNews │
│ accept transg…        ┆ - Transge…            ┆              │
│ Senior U.S.           ┆ WASHINGTON (Reuters)  ┆ politicsNews │
│ Republican senator…   ┆ - The spe…            ┆              │
│ FBI Russia probe      ┆ WASHINGTON (Reuters)  ┆ politicsNews │
│ helped by Aus…        ┆ - Trump c…            ┆              │
│ Trump wants Postal    ┆ SEATTLE/WASHINGTON    ┆ politicsNews │
│ Service to …          ┆ (Reuters) -…          ┆              │
└───────────────────────┴───────────────────────┴──────────────┘

In [11]:
fake_df.head()

shape: (5, 4)
┌─────────────────┬─────────────────┬─────────┬────────────────┐
│ title           ┆ text            ┆ subject ┆ date           │
│ ---             ┆ ---             ┆ ---     ┆ ---            │
│ str             ┆ str             ┆ str     ┆ str            │
╞═════════════════╪═════════════════╪═════════╪════════════════╡
│ Donald Trump    ┆ Donald Trump    ┆ News    ┆ December 31,   │
│ Sends Out       ┆ just couldn t   ┆         ┆ 2017           │
│ Embarr…         ┆ wis…            ┆         ┆                │
│ Drunk Bragging  ┆ House           ┆ News    ┆ December 31,   │
│ Trump Staffer … ┆ Intelligence    ┆         ┆ 2017           │
│                 ┆ Committee C…    ┆         ┆                │
│ Sheriff David   ┆ On Friday, it   ┆ News    ┆ December 30,   │
│ Clarke Becomes  ┆ was revealed    ┆         ┆ 2017           │
│ …               ┆ tha…            ┆         ┆                │
│ Trump Is So     ┆ On Christmas    ┆ News    ┆ December 29,   │
│ Obsessed He     ┆ day, Donald     ┆         ┆ 2017           │
│ Even …          ┆ Trump…          ┆         ┆                │
│ Pope Francis    ┆ Pope Francis    ┆ News    ┆ December 25,   │
│ Just Called Out ┆ used his annual ┆         ┆ 2017           │
│ …               ┆ C…              ┆         ┆                │
└─────────────────┴─────────────────┴─────────┴────────────────┘

In [12]:
fake_df = fake_df.drop("date")
fake_df.head()

shape: (5, 3)
┌──────────────────────────┬─────────────────────────┬─────────┐
│ title                    ┆ text                    ┆ subject │
│ ---                      ┆ ---                     ┆ ---     │
│ str                      ┆ str                     ┆ str     │
╞══════════════════════════╪═════════════════════════╪═════════╡
│ Donald Trump Sends Out   ┆ Donald Trump just       ┆ News    │
│ Embarr…                  ┆ couldn t wis…           ┆         │
│ Drunk Bragging Trump     ┆ House Intelligence      ┆ News    │
│ Staffer …                ┆ Committee C…            ┆         │
│ Sheriff David Clarke     ┆ On Friday, it was       ┆ News    │
│ Becomes …                ┆ revealed tha…           ┆         │
│ Trump Is So Obsessed He  ┆ On Christmas day,       ┆ News    │
│ Even …                   ┆ Donald Trump…           ┆         │
│ Pope Francis Just Called ┆ Pope Francis used his   ┆ News    │
│ Out …                    ┆ annual C…               ┆         │
└──────────────────────────┴─────────────────────────┴─────────┘

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

In [7]:
from sentence_transformers import SentenceTransformer

In [10]:
# model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
model = SentenceTransformer("Alibaba-NLP/gte-large-en-v1.5", device=device, trust_remote_code=True)

configuration.py: 0.00B [00:00, ?B/s]

D:\University\Courses\SEM 6\NLP\Project\fake_news_verifier\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sasmi\.cache\huggingface\hub\models--Alibaba-NLP--new-impl. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
[transformers] A new version of the following files was downloaded from https://huggingface.co/Alibaba-NLP/new-impl:
- configuration.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling.py: 0.00B [00:00, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/Alibaba-NLP/new-impl:
- modeling.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors:   0%|          | 0.00/1.74G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/268 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

In [ ]:
fake_title_vectors = model.encode(fake_df['title'].to_list(),show_progress_bar=True)
fake_text_vectors = model.encode(fake_df['text'].to_list(), show_progress_bar=True)

In [ ]:
fake_df = fake_df.with_columns(
    title_vectorised = pl.Series(fake_title_vectors),
    text_vectorized = pl.Series(fake_text_vectors),
)

In [ ]:
fake_df.head()